{% set name = "dask-bigquery" %}
{% set version = "2024.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dask_bigquery-{{ version }}.tar.gz
  sha256: 2807bbdd934627d0ed47c58d0e7b6075af9cba7e6f2d2e4a1e2173e20e76a023

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dask >=2024.3.0
    - gcsfs
    - google-cloud-bigquery >=2.11.0
    - google-cloud-bigquery-storage
    - pandas
    - pyarrow

test:
  imports:
    - dask_bigquery
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/coiled/dask-bigquery
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read/write data from/to Google BigQuery with Dask
  doc_url: https://github.com/coiled/dask-bigquery/blob/main/README.md
  dev_url: https://github.com/coiled/dask-bigquery

extra:
  recipe-maintainers:
    - ncclementi
    - jrbourbeau
    - bnaul
